<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_noty_modal</name>
   <tag></tag>
   <elementGuidId>b524ca69-14b2-46c7-a676-a94dba4bc53b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' noty_modal ')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.noty_modal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.noty_modal</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f6a53e38-624d-4be8-a246-8e23f0de1630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>noty_modal</value>
      <webElementGuid>efaed213-fc31-431b-9ae3-74f78a665b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-b1b24a33378130968cf96dd208c665b3</value>
      <webElementGuid>c7c4a9c7-e0cd-4018-a08c-23095edd6cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' noty_modal ')]</value>
      <webElementGuid>4e4fc1de-dc8e-4888-8838-8273d05f1f70</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' noty_modal ')]</value>
      <webElementGuid>1d422e7a-4df1-4da0-8379-b1f958811c2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
