<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_contentFrame</name>
   <tag></tag>
   <elementGuidId>97406789-9898-4db3-8ef4-1a2e7d10d810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'contentFrame']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#contentFrame</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#contentFrame</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f8fe20e1-a4c3-4e73-85c8-529d0cce2ab9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentFrame</value>
      <webElementGuid>a352ca84-b9d1-49ef-b5bb-694fe8d15c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-src</name>
      <type>Main</type>
      <value>{{frameUrl}}</value>
      <webElementGuid>ceccfe3a-2b4e-4ff3-ba83-007bba1cfb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>content_obj</value>
      <webElementGuid>a000e248-7ab5-46f6-9a64-7ea059d40521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>7a4265c5-2ed0-4f7e-814b-e2256d8d9178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>fb5068f7-7599-43a6-8d4f-4338895404d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-191f93781284f0fc21281f07e8530b45</value>
      <webElementGuid>a69cab93-79fb-4091-92d9-9f4cfcc9d23f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'contentFrame']</value>
      <webElementGuid>708f0e28-7c1e-493a-b774-96f7d2cb70f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'contentFrame']</value>
      <webElementGuid>bca4d824-31df-4e43-ac33-0e5f2d8cefb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'contentFrame']</value>
      <webElementGuid>ab35eb82-b525-4560-9f87-ac89a61b8871</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
