<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_renderHier</name>
   <tag></tag>
   <elementGuidId>a0b5138b-f46b-4054-8b8a-50f6a03c108a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'renderHier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#renderHier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#renderHier</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>f7752621-9760-442a-a917-e77c86424d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>renderHier</value>
      <webElementGuid>e3c66bb6-414f-4c6c-8402-91ee7f33f46c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>227f23e2-d2a1-410d-9e91-6ed7b8d77837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>blank</value>
      <webElementGuid>b9d46285-8e03-49b1-94b5-5ba402ef3729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1036px</value>
      <webElementGuid>e2e576f1-ecf5-4110-85c5-db7268eb49b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>559px</value>
      <webElementGuid>f126b74a-cdc0-4ad4-afee-6e20498df6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d86e05bc4b2993857ec71d6d6b3b6cb7</value>
      <webElementGuid>401bd06f-81f8-4cd8-990f-5a476f7c1fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'renderHier']</value>
      <webElementGuid>44b8500f-c3e7-420c-9788-53bb8043db68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_contentFrame</value>
      <webElementGuid>1afac560-0f28-45b3-a7b4-e0c461186fc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'renderHier']</value>
      <webElementGuid>92a1d872-b152-4e34-814f-23ebbbce1a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'renderHier']</value>
      <webElementGuid>a90c252f-0d5a-4ffa-8186-480499805ac6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
