<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Surname</name>
   <tag></tag>
   <elementGuidId>3ce6bea1-39b4-4916-a964-81e40d64c851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = '_KM_VAN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_KM_VAN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Surname*&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dec84f39-5a10-4c90-a8c4-6365aee64a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46c3d554-06f9-471e-87e2-aec06dd01edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_KM_VAN</value>
      <webElementGuid>29e3c2c3-cd27-457f-b37d-45c45819164e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_KM_VAN</value>
      <webElementGuid>4fc60620-642f-45a6-8c6d-47ec272546db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control modifier-uppercase</value>
      <webElementGuid>04109f05-33f7-4e24-a669-b7ba9f4ade4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>e9457f88-f7de-4b11-a3e0-8c94ba921117</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f36d30b8d0e96a9e97a0fe0244f9181d</value>
      <webElementGuid>06c19c50-e70e-48bf-a685-716e1adb3678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = '_KM_VAN']</value>
      <webElementGuid>36d1aa91-1d41-4c3c-8ec5-e776dc91d715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_renderHier</value>
      <webElementGuid>ef8d4df2-e1fd-4342-b0d6-28e035f870fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = '_KM_VAN']</value>
      <webElementGuid>3f431bbf-245b-4be6-a7d7-503ea6a1d003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '_KM_VAN' and @id = '_KM_VAN']</value>
      <webElementGuid>920513bc-a816-4216-a66f-a1668d36ce40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
