<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID number</name>
   <tag></tag>
   <elementGuidId>0e9e2295-b670-4988-a2f8-9c60aabef580</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = '_KM_ID_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_KM_ID_NO</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;ID number*&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>95d2f216-19c7-44f8-8f8b-6c024d6bfee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>814a6dfa-7c12-40ac-8566-60b996fa1cea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_KM_ID_NO</value>
      <webElementGuid>f420df7d-8213-4d89-b247-25c34dedaac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_KM_ID_NO</value>
      <webElementGuid>98e14a9d-6c2c-49b9-bb95-c64c02d7af4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control modifier-uppercase</value>
      <webElementGuid>65c5498f-4228-4f8b-89a2-99f0a4db7900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>ef79b172-444e-4a3e-8c33-bd2d2687b5b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:return $('#frmKlante').data('Zebra_Form').filter_input('digits', event);</value>
      <webElementGuid>dfcf81f3-b90e-4a15-910c-0fa943f8f755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateID(&quot;#_KM_ID_NO&quot;,&quot;#_KM_ID_NO_VALID&quot;)</value>
      <webElementGuid>f5455a2d-b776-47d2-963a-de52315c3c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>testRegistrasielenght(&quot;#_KM_ID_NO&quot;),
					 validateID(&quot;#_KM_ID_NO&quot;,&quot;#_KM_ID_NO_VALID&quot;),
					 soekTydelik(&quot;#_KM_ID_NO&quot;,&quot;ID&quot;)</value>
      <webElementGuid>5732df82-2513-4bc8-bfe4-07d020b12edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-df2c5929cf77132dd6aaab3d8ee7b74e</value>
      <webElementGuid>6dbd0e65-1c2c-48ad-b559-5e2ad23a1fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = '_KM_ID_NO']</value>
      <webElementGuid>ed62a0c8-1bd3-48e9-bd63-d47bbdd7fc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_renderHier</value>
      <webElementGuid>bb372845-a8e6-451c-8a25-1de8fe99fde7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = '_KM_ID_NO']</value>
      <webElementGuid>6728a22b-0e54-4cda-a322-90f2b6168c6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '_KM_ID_NO' and @id = '_KM_ID_NO']</value>
      <webElementGuid>e612e598-eb2d-47dc-8715-c078ce7f1716</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
