<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1_2</name>
   <tag></tag>
   <elementGuidId>49b3d460-0696-44c7-bca5-42f9bb36eb0e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = '_KM_EPOS1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;_KM_EPOS1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email address&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>766d0845-165d-4088-b36d-fb2181ab880b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0656914c-5e57-4c3b-9882-b724d8934a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>_KM_EPOS1</value>
      <webElementGuid>806495c4-3685-4754-878b-9a71c185167a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_KM_EPOS1</value>
      <webElementGuid>0639920d-a48e-417e-8185-72a501fbeb02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control modifier-uppercase</value>
      <webElementGuid>a80b31a9-fe21-40e6-89fa-13f0ec0fb6a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>450aeaa9-1bee-49e5-828e-5372ff4a4118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8696a910-0a7b-44dd-96c5-5889f58ee1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>Clear_Epos_errors(this.id)</value>
      <webElementGuid>34ca3163-f12f-4ffe-aaae-5231d2780ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>Toets_Epos(this.id)</value>
      <webElementGuid>1e328ccd-3169-4fd4-81f5-72902c4ebe35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-1a92ce53b316ac7771023daa4e78a0f9</value>
      <webElementGuid>03ba4413-dd10-4712-8f48-ae4b570fddf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = '_KM_EPOS1']</value>
      <webElementGuid>1097d538-2a87-4bc1-bbca-11b7fe99acd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_renderHier</value>
      <webElementGuid>5464d214-068a-41cf-b93d-5c828a567ffd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = '_KM_EPOS1']</value>
      <webElementGuid>43340dec-831a-4c6e-a8cc-de7ddd2f8e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = '_KM_EPOS1' and @id = '_KM_EPOS1' and @placeholder = '1']</value>
      <webElementGuid>525e446b-171a-4250-93d0-a3d667861296</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
