<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-_DIV_PROEFB_AAND-container</name>
   <tag></tag>
   <elementGuidId>f7e8a392-f089-485a-923f-7d51783b0ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'select2-_DIV_PROEFB_AAND-container']//*[@title = '- select -']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;select2-_DIV_PROEFB_AAND-container&quot;] [title=&quot;-\ select\ -&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-_DIV_PROEFB_AAND-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6fa45ece-efb6-4cf7-aeed-060c63c7cdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>48f0c2ab-4886-4825-b7c9-25015fbb906e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-_DIV_PROEFB_AAND-container</value>
      <webElementGuid>3c9f9d92-d8b7-4b2c-b88c-1b7ef845a4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- select -</value>
      <webElementGuid>cbf83ca9-39ed-429a-9a0c-ee8b224b815a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- select -</value>
      <webElementGuid>74e9c68d-1e91-4977-b0f5-301c5c79c9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-970bc62a4b782a19e31d059e18f7233a</value>
      <webElementGuid>caf5c755-b443-41df-a503-20ef115a8529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-_DIV_PROEFB_AAND-container']//*[@title = '- select -']</value>
      <webElementGuid>539758e7-c9c8-46dc-ac6b-753e20b4105e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_renderHier</value>
      <webElementGuid>62fdcc4f-4708-4677-8f26-266e35b74f6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-_DIV_PROEFB_AAND-container']//*[@title = '- select -']</value>
      <webElementGuid>4a5966e2-7f3c-42bb-81ee-2b209c2f5c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-_DIV_PROEFB_AAND-container' and @title = '- select -' and (text() = '- select -' or . = '- select -')]</value>
      <webElementGuid>0dbdfac3-2a98-4862-ba22-f06fdd5de443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
