<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_select2-_KM_TITEL-container</name>
   <tag></tag>
   <elementGuidId>e40e10c8-fc47-466c-89a9-5e4392a98de6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-labelledby = 'select2-_KM_TITEL-container']//*[@title = '- select -']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-labelledby=&quot;select2-_KM_TITEL-container&quot;] [title=&quot;-\ select\ -&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#select2-_KM_TITEL-container</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e5e9f904-0faf-4e1f-8d62-ccda330102fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection__rendered</value>
      <webElementGuid>c51c59b3-f932-4984-9a84-4e6335c2f4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>select2-_KM_TITEL-container</value>
      <webElementGuid>a3f07064-87fa-4c27-9c47-7ca975b0e6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>- select -</value>
      <webElementGuid>d154859c-7307-4c14-9d98-b12d79885c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>- select -</value>
      <webElementGuid>6a6d5019-a5cc-4d80-b29f-36b022f5acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cd9209c045d895360084fd3d0278d595</value>
      <webElementGuid>d6f72f8a-a074-4cc2-abef-a35b93306013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-_KM_TITEL-container']//*[@title = '- select -']</value>
      <webElementGuid>b2629c06-9641-47b9-9d55-a007fa5dd434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/create client/Page_NWK ERP/iframe_renderHier</value>
      <webElementGuid>b6916c4b-0473-4ee6-96ff-298bc7a59d33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-labelledby = 'select2-_KM_TITEL-container']//*[@title = '- select -']</value>
      <webElementGuid>b5e674d3-3f02-4ef0-bd93-21ff01bf2172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'select2-_KM_TITEL-container' and @title = '- select -' and (text() = '- select -' or . = '- select -')]</value>
      <webElementGuid>ed2374a6-256e-4b89-aadc-27720c5d070d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
