<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_uname</name>
   <tag></tag>
   <elementGuidId>9bde9b38-143b-490a-bbcd-1b6788cbd394</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#uname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='uname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Username:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e058b0a-8426-4701-9db9-ae822d9f014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5e41518f-4e66-4ff5-9ce3-17a160ee462a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>34d6b309-9b1b-4b60-a5ba-7a6c348b2cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>test</value>
      <webElementGuid>e268c65e-602f-435d-a566-66847d0aa29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>uname</value>
      <webElementGuid>aeedc5a7-985a-4736-b4b9-d098e088bf2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uname&quot;)</value>
      <webElementGuid>946e412f-bb26-4774-abb3-82d5c6fa5ac7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='uname']</value>
      <webElementGuid>9e464ac1-bd6c-46aa-9dd1-7a371ca92381</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>1d1ac6b5-b54d-4b5e-bdc4-cf7b5f4dedcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'uname' and @placeholder = 'test' and @name = 'uname']</value>
      <webElementGuid>c803522b-e196-4f96-ab07-bdecad6030d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
