<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__pwdWagwoord</name>
   <tag></tag>
   <elementGuidId>5ba8fd3a-203b-4374-91a3-b0d1dfbe941c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pwdWagwoord</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='pwdWagwoord']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Wagwoord / Password*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2e1e2a4e-8b23-4c17-b718-b0e3ce144a52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>02c21647-4e5e-4d5b-bcb5-0d255e9ff5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwdWagwoord</value>
      <webElementGuid>22eb84e0-a5a5-42c7-9588-2e1e956cc8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwdWagwoord</value>
      <webElementGuid>caf73990-03ed-4a6f-ba00-2e0177735727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control</value>
      <webElementGuid>f75a5ad0-9e76-40aa-8acc-f921822c4adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>80e8a2a7-bca1-494a-822e-4d508d49003c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>clearErrors(event)</value>
      <webElementGuid>9089c01d-c257-44e2-bc15-b531ab62d387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>checkInvalid(this)</value>
      <webElementGuid>0328688d-e273-40b3-a0b1-372fd4dde7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>d2f2abcc-7e5d-43d0-8bf3-08736c0a24c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pwdWagwoord&quot;)</value>
      <webElementGuid>21858ece-057a-4f5b-9a7e-8fa7f460d2b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='pwdWagwoord']</value>
      <webElementGuid>cd99bd9f-2d9f-48f3-9493-1e35561cfb43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enkodeer']/div[2]/div[4]/div[3]/input</value>
      <webElementGuid>7e452bd5-ac0b-449f-ae0e-64683d75c4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>1c81af3c-77ab-42ab-b816-cc7f658faf14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pwdWagwoord' and @id = 'pwdWagwoord']</value>
      <webElementGuid>e5680c2e-2425-46b0-adfc-3eb0b8446d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
