<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__txtGebruiker</name>
   <tag></tag>
   <elementGuidId>8f2f7a03-f5e6-4385-8e8e-341fc69ccd34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#txtGebruiker</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtGebruiker']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Personeelnommer / Employee number*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0754a9a1-9eff-49f0-bcdc-6fa22601909d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b7e0f6e-30ba-4b10-a285-c8f9453fb445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtGebruiker</value>
      <webElementGuid>ae6b4132-5e3d-4097-9230-07b2c4282d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtGebruiker</value>
      <webElementGuid>2ca0f3cb-ab97-4eca-875c-1f7b4f3b40f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control</value>
      <webElementGuid>bed11f77-32be-4491-9158-89c68909df50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fa37dd82-5f10-4da2-8229-e68e6a5e355a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autofocus</name>
      <type>Main</type>
      <value>autofocus</value>
      <webElementGuid>27d99280-98eb-46c4-a12f-506aeffa27b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>clearErrors(event)</value>
      <webElementGuid>699122b7-0744-4872-9ec0-20a492bd9d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>validateLength(this,7)</value>
      <webElementGuid>93a011d6-6130-4892-8467-77c55b18120a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>javascript:return $('#enkodeer').data('Zebra_Form').filter_input('digits', event);</value>
      <webElementGuid>72822483-de7b-477e-a443-528ff3bb615f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>d0be2cc4-afee-4229-9467-11ac26367fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtGebruiker&quot;)</value>
      <webElementGuid>f598bf57-0c1e-4cc3-ad40-a89355c525a1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtGebruiker']</value>
      <webElementGuid>474c77b1-60be-4bea-870d-36359f8fbcd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enkodeer']/div[2]/div[2]/div[4]/input</value>
      <webElementGuid>d14d1b30-1b95-47e6-920a-3fb9a2a63612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>ed9b7963-ab12-4098-9798-18469a5cf48c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'txtGebruiker' and @id = 'txtGebruiker']</value>
      <webElementGuid>7556dacd-45a3-4366-9860-8d52086b91bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
