<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Wagwoord _ Password</name>
   <tag></tag>
   <elementGuidId>e11bd867-23b6-4119-b037-af767a0fb009</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'pwdWagwoord']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pwdWagwoord</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Wagwoord / Password*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b2984774-9538-4870-ac7c-7ddd7a535c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f9a170f-7e98-400e-9bce-775db72dc25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pwdWagwoord</value>
      <webElementGuid>624211eb-81bd-4af3-ba54-176a49c15756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pwdWagwoord</value>
      <webElementGuid>8e5b87ad-508f-401d-ae93-0e3c4f82b1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-field control form-control</value>
      <webElementGuid>2b865cbb-75cf-4bcc-90d1-1df319a64c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e1924668-b8ac-44ba-96e1-bf1317f8f64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>clearErrors(event)</value>
      <webElementGuid>4ac2f71c-1f1a-476b-a9e7-70e5425c20ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>checkInvalid(this)</value>
      <webElementGuid>e2edf5af-f6b0-4d41-82a6-29d3a16e1b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>727f8764-1b3d-4933-a520-2db2784b25dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-67dc085a51584968127be8bf584b445a</value>
      <webElementGuid>316be8f4-00b0-40c7-87e3-9937e3ae9e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'pwdWagwoord']</value>
      <webElementGuid>d6f29509-45a5-4848-af9d-1cddf5104f5f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'pwdWagwoord']</value>
      <webElementGuid>eabee97b-64b1-40b1-be59-f7f336bd156e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'pwdWagwoord' and @id = 'pwdWagwoord']</value>
      <webElementGuid>bdd6c0a2-8797-48e0-899c-5cbcb2bc6cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
